services:
    admin-backend:
        build:
            context: ../apps/admin-backend
        env_file:
            - ./.env
        volumes:
            - ../vault:/vault
        expose:
            - 8000

    frontend:
        build:
            context: ../apps/frontend
            dockerfile: .Dockerfile
        env_file:
            - ./.env
        expose:
            - 3000

    caddy:
        image: caddy:2-alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ../vault:/vault:ro
            - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
        depends_on:
            - admin-backend
            - frontend

networks:
    default:
        name: sasha-local
