services:
    admin-backend:
        build:
            context: ../apps/admin-backend
            dockerfile: .Dockerfile.dev
        working_dir: /app
        env_file:
            - ./.env
        environment:
            - PYTHONPATH=/app
            - WATCHFILES_FORCE_POLLING=true
        volumes:
            - ../apps/admin-backend:/app
            - ../vault:/vault
        expose:
            - 8000
        command: >
            bash -lc "poetry install --no-ansi --with dev && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app --access-log --log-level info"


    # frontend:
    #     build:
    #         context: ../apps/frontend
    #         dockerfile: .Dockerfile
    #     env_file:
    #         - ./.env
    #     expose:
    #         - 3000
    frontend:
        build:
            context: ../apps/frontend
            dockerfile: .Dockerfile.dev
        working_dir: /app
        env_file:
            - .env
        expose:
            - 3000
        volumes:
            - ../apps/frontend:/app            
            - /app/node_modules 
        environment:
            - CHOKIDAR_USEPOLLING=true  
        command: sh -c "[ -d node_modules ] || npm install --no-audit --no-fund && npx vite --host 0.0.0.0 --port 3000"

    caddy:
        image: caddy:2-alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ../vault:/vault:ro
            - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
        depends_on:
            - admin-backend
            - frontend

networks:
    default:
        name: sasha-local
